### ISSUE TITLE
How do you disable libvlc logging output for a MediaPlayer object?

### ISSUE THREAD

**Issue by hillt03** [oaubert/python-vlc#119]
I've tried the following:

`self.vlc_player = vlc.MediaPlayer("--verbose=-1)`
`self.vlc_player = vlc.MediaPlayer("--verbose -1")`

`self.vlc_player.set_mrl(song_url, "--verbose=-1")`
`self.vlc_player.set_mrl(song_url, "--verbose -1") `

But I still get this error printed in my console window with seemingly no other side effects or issues caused by it:  

```
[000002acd48e1c00] mp4 demux: Fragment sequence discontinuity detected 1 != 0
[000002acd48e1960] adaptive demux error: Failed to create demuxer 0000000000000000 Unknown
[000002acd48e1ea0] mp4 demux: Fragment sequence discontinuity detected 1 != 0
[000002acd48e1ea0] mp4 demux: Fragment sequence discontinuity detected 1 != 2
[000002acd48e1960] adaptive demux error: Failed to create demuxer 0000000000000000 Unknown
[000002acd48e1ea0] mp4 demux: Fragment sequence discontinuity detected 1 != 2
```

Is this possible? I'm working on a CLI app and it's a rather annoying issue, albeit it's rare and doesn't occur with every song I try to play.

**Comment by rickie95** [comment]
I've the same behavior, trying with suppressing stdout and stderr works but now I'm unable to print anything. I'll try to embed the player in a separate thread.

I'm afraid that the verbose argument works only on VLC itself, and not on his dependencies/libraries.

**Comment by hillt03** [comment]
> I'm afraid that the verbose argument works only on VLC itself, and not on his dependencies/libraries.

Good to know, especially considering my other arguments are working just fine. Using a separate thread sounds like a good idea and would be a pretty simple workaround, update with how it works out. Otherwise, I'll try it myself when I have the time to work on my app.

**Comment by oaubert** [comment]
The verbose parameter works in libvlc (try setting it to 2 or 3, you will see the difference). The trouble here is that the libvlc API only proposes 0 (info), 1 (error), 2 (warning) and 3 (debug) as valid values (it is not in the documentation, I looked up in the source, but you can also get it through `vlc --full-help`). -1 is supposed to meant "default" and not "disable everything", when called through this code path. However, I can find in the VLC code some references to -1 disabling all output, but since the verbose argument is processed in the logger stack, it looks like the "-1 as default" behaviour prevents the actual value to be set.

Looking at https://code.videolan.org/videolan/vlc/blob/master/modules/logger/console.c#L141 there is a reference to getting the value from the VLC_VERBOSE environment variable, which should be passed as is (and directly after, a test for verbosity < 0). You should test it.

**Comment by mrJean1** [comment]
Using env VLC_VERBOSE=-1 or =-2 does seem to disable […] main ... error … messages and similar ones.  However, other message like [h264 @ …] get_buffer() failed and the like still appear.  This is with vlc.py 3.0.7110 with libVLC 3.0.8 Vetinari and Python 3.8.1 on macOS 10.13.6.

**Comment by rickie95** [comment]
As @oaubert suggested setting VLC_VERBOSE to -1 prevents message in my situation.
```
os.environ["VLC_VERBOSE"] = str("-1")
player = vlc.MediaPlayer(a_mp4_url)
player.play()
```
Might be appropriate to restore it on program's exit.

Tested with VLC 3.0.8, python-vlc 3.0.7110 on Ubuntu 19.10. 

Scenarios with no messages at all:
- http stream (m3u8 url). 
- Audio files: mp3, wav, flac, ogg, aif
- flv (FLV1 + mp4a)

Log messages by **libva/mesa** are printed while reproducing:
- 3gp (h263 + AMR)
- mkv (mp4v + mp4a) 
- mp4 (avc1/h264 + mp4a)

**Comment by oaubert** [comment]
No need to restore the environment variable afterwards, it is only set for the current process and its potential children, not its ancestors.
