### ISSUE TITLE
How do I get the slaves list?

### ISSUE THREAD

**Issue by OctoNezd** [oaubert/python-vlc#127]
According to docs, I need to pass `ppp_slaves`, but how I am supposed to create it in first place? I cant just pass list/tuple there, I get `ctypes.ArgumentError: argument 2: <class 'TypeError'>: expected LP_LP_MediaSlave instance instead of list` thrown, and I cant find that LP_LP_MediaSlave reference anywhere in in `vlc.py`

**Comment by oaubert** [comment]
You have to pass a `ctypes.POINTER` to a `MediaSlave` class. You can see how it is done for `Media.tracks_get` in https://github.com/oaubert/python-vlc/blob/master/generator/templates/override.py#L174
To fix this in the vlc module, a `slaves_get` method wrapper should be defined in the same way and same file. Would you be interested to have a go at it, so that it benefits the community?

**Comment by OctoNezd** [comment]
I realised that using video_get_spu_description will be much better in my usecase, so I dont need slaves_get. 
I, however, still tried to make my own slaves_get same way like tracks_get, but it threw me cast errors, so I dont really understand how all that ctypes stuff work
