### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by renekliment** [oaubert/python-vlc#15]
Please update the PyPI package.
Thank you.

**Comment by hickford** [comment]
The most release at https://pypi.python.org/pypi/python-vlc/ is 1.1.2 uploaded November 2015

**Comment by oaubert** [comment]
This issue is still on my todo list but doing it properly requires time that I currently do not have: the bindings are automatically generated from the include files. The parser/generator code is the actual code I produce (and thus release), but users expect to simply install a vlc.py module that works. So writing a setup.py to produce a pypi installable module is different from conventional projects. On top of that, there are (at least) 2 versions of the generated module that may be relevant: the stable one, generated from vlc 2.2 headers, and the development one, generated from the development version of vlc. This complicates things, in scripting and in versioning schemas too.
The most reasonable option is to put the stable (currently 2.2) generated bindings on pypi. Which is what will happen when I (or some contributor) find the time to properly tweak the setup.py file.

**Comment by renekliment** [comment]
@oaubert Hello, could you please have a look at this if you find some free time?

**Comment by oaubert** [comment]
Hello. This issue is not forgotten, but time is scarce...

**Comment by renekliment** [comment]
@oaubert I hate to bug you about this, but is there any chance this can happen? Thank you.

**Comment by oaubert** [comment]
I am still pondering this issue, sharing thoughts here. I have converted parts of the package generator to generate an installable module (generating setup.py, etc) which could be then directly injected into PyPI. My main issue now is versioning. The current situation is:

- VLC has a 3-part version number (2.2.6 currently) 
- the bindings generator has a version number (20.17.09.25 currently). I could either change it to 20170925, or switch to a major.minor scheme e.g. 1.0, which would indicate releases more precisely.
- Debian packages (since I am also dealing with debian package building) also have a debian revision.

So the generated python-vlc version, for the 2.2.6 libvlc includes using the 20.17.0.25 generator, would be
2.2.6-20.17.09.25 (and the debian package would be 2.2.6-20.17.09.25_1) which is rather ugly, even if it matches Debian Policy.
If I switch to major.minor for the generator, this would give 2.2.6-1.0_1 which may be acceptable.

*but* (writing this just after implementing the above proposal for generating files for PyPI package building) here comes PEP 440, which has strong constraints on version numbers for PyPI packages. They MUST be of the form
[N!]N(.N)*[{a|b|rc}N][.postN][.devN]

so I have to somehow find a way to massage 2 version numbers into one, because I think it is a desirable property to be able to clearly identify the vlc version matching the package.

The solution I am contemplating now is to generate the major number from the VLC version number, and the minor from the generator version, i.e.

bindings_major = 10000 * vlc_major + 100 * vlc_minor + vlc_micro
bindings_minor = 100 * generator_major + generator_minor

which would give for the current situation (vlc 2.2.6, generator 1.0) a version number of
20206.100

This holds as long as micro and minor revision numbers for vlc and generator are below 100.

Any thoughts?

**Comment by oaubert** [comment]
2 other options:
- do not care about vlc and generator version numbers, and have python-vlc have its own major/minor. Specifying dependencies will be the job of documentation and packages.
- use vlc_major.vlc_minor.(100*vlc_micro + bindings release) (which would be 2.2.601 for current version, 2.2.602 for next one, etc). This does not take into account the generator version number (which is not relevant for users anyway), but still indicates which vlc version it was built with.

**Comment by renekliment** [comment]
Mmm, this is a tough one.

I say let python-vlc have its own versioning and specify VLC version in dependencies. When adhering to the PEP, there is no nice solution and the python package is a package itself, so why not.

**Comment by oaubert** [comment]
Alright, I decided for yet another scheme: the bindings version number will be
vlc_major.vlc_minor.(1000*vlc_micro + 100 * generator_major + generator_minor)
which makes it 2.2.6100 for the first release using this scheme. The IMO nice property of this is that the bindings share the same major/minor as the VLC version they where generated against.
