### ISSUE TITLE
[Question] Why can't I have a child class for vlc.MediaPlayer?

### ISSUE THREAD

**Issue by sequeirayeslin** [oaubert/python-vlc#175]
```
import vlc

class ChildMediaPlayer(vlc.MediaPlayer):
    def random_method(self):
        pass

player = ChildMediaPlayer()
player.random_method()
```

The above code gives me this error:

```
Traceback (most recent call last):
  File "C:\Users\seque\play\vlcSyncApp\Host\test.py", line 9, in <module>
    player.random_method()
AttributeError: 'MediaPlayer' object has no attribute 'random_method'
```

I can call the parent's methods just fine, eg. .get_length(), .set_media(), but I can't call the ones I created.

Sorry if this is a silly question. I've been using python for only a few months.

**Comment by oaubert** [comment]
This is because the `__new__` method of the MediaPlayer class is used so that it returns a proper wrapper around the libvlc_mediaplayer structure when instanciating the class (or its subclasses). It is used to maintain appropriate mappings between the python API and the original C API.
You could use a delegation approach instead: store the vlc.MediaPlayer as an attribute of your own class, and delegate methods to it. You could even do it dynamically, through the `__getattr__` method, something like
```
def __getattr__(self, name):
    return getattr(sefl.mediaplayer, name)
```

**Comment by sequeirayeslin** [comment]
Thank you!
