### ISSUE TITLE
is there any way to play video loaded to memory using python-vlc?

### ISSUE THREAD

**Issue by redstoneleo** [oaubert/python-vlc#88]
Any way to play bytes object in python-vlc? For example , how to  play the contents in Axel in the following ?
```
File1 = open('vid.webm','rb')
Axel  = File1.read()
```

**Comment by oaubert** [comment]
You should use the `Media.new_callbacks` API. You can find examples in C, e.g. https://stackoverflow.com/questions/31250640/using-vlc-imem-to-play-an-h264-video-file-from-memory-but-receiving-error-main and adapt them in python. Once you are done, you can contribute your code so that I can add it to the repository examples.

**Comment by albestro** [comment]
I'm working on a very basic project for playing an audio stream from the internet, and I'm using `media_new_callbacks`. It should be equivalent to playing any other kind of media.

I've just opened issue #117 about a problem I had, in case I can share my sample code as an example.
