### ISSUE TITLE
vlm i_instance parameter not needed

### ISSUE THREAD

**Issue by postelrich** [oaubert/python-vlc#9]
All of the Instance().vlm_get_media_instance_XXX functions require both a psz_name and i_instance.  When using vlm for a broadcast or vod, you can play, stop, pause, and change the media with just the psz_name. But to get position, you also need the i_instance (instance id) which can't be gotten from anywhere.

**Comment by oaubert** [comment]
This is not a python-specific question, since the problems lies in the native libvlc API. I never used the VLM API, but it is strange indeed. If you look at the source code (lib/vlm.c) you will see that all functions begin by calling libvlc_get_media_instance but this function is itself not available through the API. 
On the other hand, from the documentation (that states "by name or instance id") I would guess that the instance id is optional if you specify the instance name.
Anyway, you should ask this question on vlc-devel or forum.videolan.org, but about the libvlc_vlm_* API rather than specifically the python bindings.

**Comment by postelrich** [comment]
Yes, it says either or but its you definitely need to both if you look at libvlm_get_media_instance c code.

Why not add some function that lets you get all current media instances attached an instance?

https://github.com/videolan/vlc/blob/master/lib/vlm.c#L175

**Comment by oaubert** [comment]
Looking at the code, the instance id will not be used if < 0 (see https://github.com/videolan/vlc/blob/master/lib/vlm.c#L182 ). But anyway, you raise a valid point about the impossibility to get the media instance id, which makes this parameter basically useless. This should definitely be reported on vlc-devel, since it is a shortcoming of the native libvlc API.

**Comment by postelrich** [comment]
I tried setting instance_id to -1 but that didn't work.  Makes sense because if you look at https://github.com/videolan/vlc/blob/master/lib/vlm.c#L181, p_minstance, the return value, is NULL and only set if instance id > 0.  I sent an email to vlc-devel.
